services:
  - type: web
    name: dementia-risk-app
    env: python
    buildCommand: pip install -r z1requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
